version: '3.8'

services:
  tuteduce_ec2:
    build: .
    container_name: tuteduce_ec2
    ports:
      - "5000:5000"   # main app port
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
